language: go
go:
  - "1.10"
  - "1.11"

before_install:
  - PKGS=$(go list ./... )             # All the import paths
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # go dep
  - go get -u github.com/golang/lint/golint              # Linter
  - go get -u github.com/kisielk/errcheck                # errcheck checks that you checked errors.

install:
  - dep ensure

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - go test -v $PKGS
